region: ap-northeast-1

function_name: argomi-upload-initialize
handler: service.handler
description: Initializes the upload state machine
runtime: python3.6
role: lambda_execution

# S3 upload requires appropriate role with s3:PutObject permission
# (ex. basic_s3_upload), a destination bucket, and the key prefix
bucket_name: 'argomi-upload-deployment'
s3_key_prefix: 'initialize-'

# if access key and secret are left blank, boto will use the credentials
# defined in the [default] section of ~/.aws/credentials.
# aws_access_key_id:
# aws_secret_access_key:

# dist_directory: dist
timeout: 30
# memory_size: 512
#

# Experimental Environment variables


# Build options
# build:
#   source_directories: lib # a comma delimited list of directories in your project root that contains source to package.
